
  export const productRows = [
    {
      id: 1,
      from: "Carnet d'un permissionnaire. Paris : Devambez, 1917",
      name: "Le thé-tricot",
      departement: "Littérature et art",
      category: "Textes imprimés et illustrés",
      date: 1917,
      height: 1993,
      weight: 2541,
      autor: "Guy Arnoux",
      life: "1886-1951",
      role: "illustrator",
      img:'/tableaux/1.jpg',
      stock: 123,
      status: "active",
      price: 120.00,
    },
    {
      id: 2,
      from: "Carnet d'un permissionnaire. Paris : Devambez, 1917",
      name: "Les nouveaux riches",
      departement: "Littérature et art",
      category: "Textes imprimés et illustrés",
      date: 1917,
      height: 2021,
      weight: 2563,
      autor: "Guy Arnoux",
      life: "1886-1951",
      role: "illustrator",
      img:'/tableaux/2.jpg',
      stock: 123,
      status: "active",
      price: 120.00,
    },
    {
      id: 3,
      from: "Le Livre des mille nuits et une nuit. T I. - Paris : impr. Kadar ; édition... art H. Piazza, 1926. In-4°",
      name: "La fumée sortit, se condensa et devint un éfrit",
      departement: "Réserve des livres rares",
      category: "Textes imprimés et illustrés",
      date: 1926,
      height: 4850,
      weight: 3410,
      autor: "Léo Carré",
      life: "1878-1942",
      role: "illustrator",
      img:'/tableaux/3.jpg',
      stock: 123,
      status: "active",
      price: 100.00,
    },
    {
      id: 4,
      from: "Le Livre des mille nuits et une nuit. Tome I. - Paris : impr. Kadar ; édition... art H. Piazza, 1926. - In-4",
      name: "Le cheval étendit deux grandes ailes noires et s'envola",
      departement: "Réserve des livres rares",
      category: "Textes imprimés et illustrés",
      date: 1926,
      height: 4796,
      weight: 3532,
      autor: "Léo Carré",
      life: "1878-1942",
      role: "illustrator",
      img:'/tableaux/4.jpg',
      stock: 123,
      status: "active",
      price: 120.00,
    },
    {
      id: 5,
      from: "Le Livre des mille nuits et une nuit. Tome 10. - Paris : impr. Kadar ; H. Piazza, 1931. In-4°",
      name: "Il put examiner quelle pouvait être l'affaire",
      departement: "Réserve des livres rares",
      category: "Textes imprimés et illustrés",
      date: 1931,
      height: 4776,
      weight: 3516,
      autor: "Léo Carré",
      life: "1878-1942",
      role: "illustrator",
      img:'/tableaux/5.jpg',
      stock: 123,
      status: "active",
      price: 120.00,
    },
    {
      id: 6,
      from: "Pas sur la bouche ! opérette en 3 actes pour piano et chant",
      name: "Pas sur la bouche !",
      departement: "Musique",
      category: "Textes imprimés et illustrés",
      date: 1925,
      height: 2697,
      weight: 2010,
      autor: "André Barde",
      life: "1874-1945",
      role: "Parolier",
      img:'/tableaux/6.jpg',
      stock: 123,
      status: "active",
      price: 120.00,
    },
    {
      id: 7,
      from: "Le Livre des mille nuits et une nuit. tome 7. - Paris : impr. Kadar ; H. Piazza, 1929. In-4°",
      name: "Viens, ô pêcheur, ne me fuis pas !",
      departement: "Réserve des livres rares",
      category: "Textes imprimés et illustrés",
      date: 1929,
      height: 4726,
      weight: 3582,
      autor: "Léon Carré",
      life: "1878-1942",
      role: "illustrator",
      img:'/tableaux/7.jpg',
      stock: 123,
      status: "active",
      price: 120.00,
    },
    {
      id: 8,
      from: "Le Livre des Mille nuits et une nuit. Tome 9. - Paris, impr. Kadar ; H. Piazza, 1930. In-4°",
      name: "Je ne fus pas longtemps sans découvrir celui que je cherchais",
      departement: "Réserve des livres rares",
      category: "Textes imprimés et illustrés",
      date: 1930,
      height: 4726,
      weight: 3466,
      autor: "Léon Carré",
      life: "1878-1942",
      role: "illustrator",
      img:'/tableaux/8.jpg',
      stock: 123,
      status: "active",
      price: 120.00,
    },
    {
      id: 9,
      from: "Le Livre des Mille nuits et une nuit. Tome 9. - Paris, impr. Kadar ; H. Piazza, 1930. In-4°",
      name: "Il était possédé du désir de toujours apprendre davantage",
      departement: "Réserve des livres rares",
      category: "Textes imprimés et illustrés",
      date: 1930,
      height: 4716,
      weight: 3502,
      autor: "Léon Carré",
      life: "1878-1942",
      role: "illustrator",
      img:'../../..//tableaux/9.jpg',
      stock: 123,
      status: "active",
      price: 120.00,
    },
    {
      id: 10,
      from: "Le Livre des Mille nuits et une nuit. Tome 8. - Paris, impr. Kadar ; H. Piazza, 1930. In-4°",
      name: "Au même moment la terre trembla",
      departement: "Réserve des livres rares",
      category: "Textes imprimés et illustrés",
      date: 1930,
      height: 4776,
      weight: 3548,
      autor: "Léon Carré",
      life: "1878-1942",
      role: "illustrator",
      img:'..//tableaux/10.jpg',
      stock: 123,
      status: "active",
      price: 120.00,
    },
  ];